// Generated by CoffeeScript 1.3.3
(function() {
  var fetch;

  fetch = function() {
    var org, repo;
    org = new Gh3.User("presidential-innovation-fellows");
    repo = new Gh3.Repository("mygov", org);
    return repo.fetch(function() {
      return repo.fetchBranches(function() {
        var master;
        master = repo.getBranchByName("gh-pages");
        return master.fetchContents(function() {
          var img;
          img = master.getDirByName('images');
          return img.fetchContents(function() {
            var content;
            content = img.getDirByName('content');
            return content.fetchContents(function() {
              content.getContents();
              return content.eachContent(function(image) {
                var compiled;
                compiled = _.template($('#image_template').html());
                return $('#images').append(compiled({
                  name: image.name
                }));
              });
            });
          });
        });
      });
    });
  };

  $('.image a').live('click', function() {
    var compiled;
    compiled = _.template($('#embed_code').html());
    return $('#output').val(compiled({
      name: $(this).html(),
      alt: $('#caption').val(),
      caption: $('#caption').val(),
      credit: $('#credit').val(),
      credit_link: $('#credit_link').val()
    }));
  });

  $('#output').focus(function() {
    $(this).select();
    return $(this).mouseup(function() {
      $(this).unbind('mouseup');
      return false;
    });
  });

  fetch();

}).call(this);
